Library/Controllers/BookController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Repo.Models;
using Repo.IRepo;

namespace Library.Controllers
{
    public class BookController : Controller
    {
        private readonly IBookRepo _repo;
        private readonly ILibraryContext _context;

        public BookController(IBookRepo repo, ILibraryContext context)
        {
            _repo = repo;
            _context = context;
        }

        // GET: Book
        public ActionResult Index()
        {
            var book = _repo.GetBook();
           // var book = db.Book.Include(b => b.Category);
            return View(book);
        }

        // GET: Book/Details/5
        [Authorize]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Book book = _repo.GetBookById((int)id);
            if (book == null)
            {
                return HttpNotFound();
            }
            return View(book);
        }

        // GET: Book/Create
        [Authorize]
        public ActionResult Create()
        {
            if (User.IsInRole("Admin") || User.IsInRole("Librarian"))
            {
                ViewBag.CategoryId = new SelectList(_context.Category, "Id", "Name");
                return View();
            }
                else
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
             }

   
        }

        // POST: Book/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Isbn,Title,Author,Page,Publisher,PublicationYear,Available,CategoryId")] Book book)
        {
            if (ModelState.IsValid)
            {
                
                    try
                    {
                        _repo.AddBook(book);
                        _repo.SaveChanges();
                       return RedirectToAction("Index"); 
                    }
                    catch
                    {
                        return View(book);
                    }
                 
            }
            ViewBag.CategoryId = new SelectList(_context.Category, "Id", "Name", book.CategoryId);

            return View(book);
        }

        // GET: Book/Edit/5
        [Authorize]
        public ActionResult Edit(int? id)
        {
            if (id == null )
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Book book = _repo.GetBookById((int)id);
            if (book == null)
            {
                return HttpNotFound();
            }
            else if(!(User.IsInRole("Admin") || User.IsInRole("Librarian")))
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ViewBag.CategoryId = new SelectList(_context.Category, "Id", "Name", book.CategoryId);
            return View(book);
        }

        // POST: Book/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Isbn,Title,Author,Page,Publisher,PublicationYear,Available,CategoryId")] Book book)
        {
            if (ModelState.IsValid)
            {
                if (User.IsInRole("Admin") || User.IsInRole("Librarian"))
                {


                    try
                    {
                        _repo.Actualize(book);
                        _repo.SaveChanges();
                    }
                    catch
                    {
                        return View(book);
                    }
                }
                else
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
            }
            ViewBag.CategoryId = new SelectList(_context.Category, "Id", "Name", book.CategoryId);

            return View(book);
        }

        // GET: Book/Delete/5
        [Authorize]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Book book = _repo.GetBookById((int)id);
            if (book == null)
            {
                return HttpNotFound();
            }
            else if(!User.IsInRole("Admin"))
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            return View(book);
        }

        // POST: Book/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            _repo.DeleteBook(id);
            try
            {
                _repo.SaveChanges();
            }
            catch
            {
                return RedirectToAction("Delete");
            }
            return RedirectToAction("Index");
        }

        //protected override void Dispose(bool disposing)
        //{
        //    if (disposing)
        //    {
        //        db.Dispose();
        //    }
        //    base.Dispose(disposing);
        //}
    }
}

Library/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Repo.Models;
using System.Diagnostics;
using Repo.RepoController;
using Repo.IRepo;
using Microsoft.AspNet.Identity;

namespace Library.Controllers
{
    public class OrderController : Controller
    {
        private readonly IOrderRepo _repo;
        private readonly ILibraryContext _context;
        private readonly IBookRepo _bookRepo;

        public OrderController(IOrderRepo repo, ILibraryContext context, IBookRepo bookRepo)
        {
            _repo = repo;
            _context = context;
            _bookRepo = bookRepo;
            
        }      

        // GET: Order
        public ActionResult Index()
        {
            if(User.IsInRole("Admin") || User.IsInRole("Librarian"))
            {
                var order = _repo.GetOrder();
                return View(order);
            }
            else
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            
        }
       
        public ActionResult MyOrder()
        {
            string userId = User.Identity.GetUserId();
            var order = _repo.GetOrder();
            order = order.Where(o => o.UserId == userId);
            return View(order);
        }

        [HttpPost]
        public ActionResult AvailabilityStatus(Order model)
        {
            var id = model.BookId;

            return View();
        }   
            
        // GET: Order/Details/5
        [Authorize]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Order order = _repo.GetOrderById((int)id);
            if (order == null)
            {
                return HttpNotFound();
            }
            else if (order.UserId != User.Identity.GetUserId() && (!(User.IsInRole("Admin") || User.IsInRole("Librarian"))))
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            return View(order);
        }

        // GET: Order/Create
        [Authorize]
        public ActionResult Create(bool? error)
        {


            ViewBag.BookId = new SelectList(_context.Book, "Id", "Title");

            if (error != null)
                ViewBag.Error = true;
          

            return View();
        }

        // POST: Order/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,OrderDate,ReceptionDate,ReturnDate,UserId,BookId")] Order order, FormCollection form)
        {

            if (ModelState.IsValid)
            {

                try
                {
                    
                    var DDLValue = Int32.Parse(Request.Form["BookId"]);               
                    var availability = _bookRepo.Availability(DDLValue);
                    if (availability == "No")
                    {

                        throw new Exception();
                    }
                    else
                    {
                        
                        order.UserId = User.Identity.GetUserId();
                        order.OrderDate = System.DateTime.Now.Date;
                        DateTime date = order.OrderDate;
                        order.ReceptionDate = date.AddDays(2);
                        order.ReturnDate = date.AddDays(30);
                        

                        _repo.AddOrder(order);
                        _repo.SaveChanges();
                        _bookRepo.ChangeAvailability(order.BookId, "No");
                        _bookRepo.SaveChanges();
                    }

                }
                catch
                {              
                    ViewBag.Error = true;                  
                    return RedirectToAction("Create", new { error = true});
                }
                //ViewBag.Error = false;

                
                    ViewBag.BookId = new SelectList(_context.Book, "Id", "Title", order.BookId);

               
            }
            return RedirectToAction("MyOrder");
            }
        

        // GET: Order/Edit/5
        [Authorize]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Order order = _repo.GetOrderById((int)id);
            if (order == null)
            {
                return HttpNotFound();
            }
            else if( !(User.IsInRole("Admin") || User.IsInRole("Librarian") ))
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
        
            ViewBag.BookId = new SelectList(_context.Book, "Id", "Title", order.BookId);
            ViewBag.UserId = new SelectList(_context.User, "Id", "Email", order.UserId);

            return View(order);
        }

        // POST: Order/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,OrderDate,ReceptionDate,ReturnDate,UserId,BookId")] Order order)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    _repo.Actualize(order);
                    _repo.SaveChanges();
                }
                catch
                {
                    ViewBag.Error = true;
                    return View(order);
                }           
             
            }
            ViewBag.BookId = new SelectList(_context.Book, "Id", "Title", order.BookId);
            ViewBag.UserId = new SelectList(_context.User, "Id", "Email", order.UserId);

            ViewBag.Error = false;
            return View(order);
        }

        // GET: Order/Delete/5
        [Authorize]
        public ActionResult Delete(int? id, bool? error)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Order order = _repo.GetOrderById((int)id);
            if (order == null)
            {
                return HttpNotFound();
            }
            else if(order.UserId != User.Identity.GetUserId() && !(User.IsInRole("Admin") || User.IsInRole("Librarian")))
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            if (error != null)
                ViewBag.Error = true;
            return View(order);
        }

        // POST: Order/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult DeleteConfirmed(int id)
        {
            
            try
            {
                Order order = _repo.GetOrderById((int)id);

                _bookRepo.ChangeAvailability(order.BookId, "Yes");
                 _repo.DeleteOrder(id);
                _repo.SaveChanges();
                _bookRepo.SaveChanges();
            }
            catch
            {
                return RedirectToAction("Delete", new { id = id, error = true });
            }
           
            return RedirectToAction("MyOrder");
        }

        //protected override void Dispose(bool disposing)
        //{
        //    if (disposing)
        //    {
        //        db.Dispose();
        //    }
        //    base.Dispose(disposing);
        //}
    }
}

Library/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title </title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    @*<script src="@Url.Content("~/Scripts/jquery.min.js")"></script>
    <script src="@Url.Content("~/Scripts/bootstrap.js")"></script>
    @RenderSection("Scripts", false/*required*/)*@
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
               

                @Html.ActionLink("School Library", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
               
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                   
                    <li><a href=@Url.Action("Index", "Home")> <i class="fa fa-home fa-2x"> </i></a></li>

                  
    @if (User.Identity.IsAuthenticated)
    {
        <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Orders<span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
                @if (User.IsInRole("Admin") || User.IsInRole("Librarian"))
                {
                    <li>@Html.ActionLink("All Orders", "Index", "Order")</li>
                }
                    

                <li> @Html.ActionLink("New Order", "Create", "Order")</li>
                <li> @Html.ActionLink("My Orders", "MyOrder", "Order")</li>

            </ul>
        </li>
    }
    else
    {
                    <li>@Html.ActionLink("Order", "Login", "Account")</li>
                    
    }
              
                    

                 
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Categories<span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">
                            @if (User.IsInRole("Admin") || User.IsInRole("Librarian"))
                            {
                                <li>@Html.ActionLink("Add Category", "Create", "Category")</li>
                            }
                            <li>@Html.ActionLink("Display Categories", "Index", "Category")</li>

                            
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Books<span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">
                            @if (User.IsInRole("Admin") || User.IsInRole("Librarian"))
                            {
                                <li>@Html.ActionLink("Add Book", "Create", "Book")</li>
                            }
                     
                            <li>@Html.ActionLink("Display Books", "Index", "Book")</li>

                        </ul>
                    </li>


                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            @*<p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>*@
        </footer>
    </div>
        <footer>
            <div class="footer">
                <div class="container">
                    <div class="social-icon">
                        <div class="col-md-3">
                            <ul class="social-network">
                                <li><a href="#" class="fb tool-tip" title="Facebook"><i class="fa fa-facebook"></i></a></li>
                                <li><a href="#" class="instagram tool-tip" title="Instagram"><i class="fa fa-instagram"></i></a></li>
                                <li><a href="#" class="linkedin tool-tip" title="Linkedin"><i class="fa fa-linkedin"></i></a></li>

                            </ul>
                        </div>
                    </div>


                    <div class="col-md-3">
                        <div class="footerContact">
                            <p><i class="fa fa-map-marker"></i> School Library</p>
                            <p>ul.Radzikowskiego 80</p>
                            <p>31-315 Cracow</p>
                        </div>

                    </div>
                    <div class="col-md-3">
                        <div class="footerContact">
                            <p><i class="fa fa-phone"></i>+48 692 385 525</p>
                            <p><i class="fa fa-envelope"></i> school.library@gmail.com</p>
                        </div>

                    </div>
                    <div class="col-md-3">
                        <div class="footerContact">
                            <p>Monday to Friday</p>
                            <p>8.00 - 15.00</p>
                        </div>

                    </div>

                    
                </div>

                @*<div class="pull-right">
                    <a href="#home" class="scrollup"><i class="fa fa-angle-up fa-3x"></i></a>
                </div>*@
            </div>
        </footer>



    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>